name: jewelry_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^7.1.1
  firebase_app_check: ^0.3.2+4
  google_sign_in_web: ^0.12.4+4
  flutter_facebook_auth_web: ^6.1.2
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.5
  firebase_core_web: ^2.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/facebook.png
